### ISSUE TITLE
Create technology review

### ISSUE THREAD

**Issue by toddschultz** [toddschultz/DegreesOfClimateChange#14]
Create technology review markdown and powerpoint files looking at web scraping modules and visualization modules. 

## Web scraping
* requests
* pandas.read_csv
* linux 'curl' command
* BeautifulSoup
* Flask

## Visualization
* Matplotlib
* Dash
* ?

**Comment by toddschultz** [comment]
Good work on the technology review markdown. Let's keep going and finish it up!

**Comment by abhishekanand** [comment]
Added some context around Visualization

**Comment by toddschultz** [comment]
Looks good be we need a pro/con slide for Beautiful Soup.

**Comment by toddschultz** [comment]
Presentation done.
