### ISSUE TITLE
Design document should detail components

### ISSUE THREAD

**Issue by joseph-hellerstein** [toddschultz/DegreesOfClimateChange#15]
# Issue Template

## Context
At present, the design document describes a workflow for data collection. You should describe what you need to build to accomplish data collection, analysis, and visualization.

**Comment by toddschultz** [comment]
Created Components.md in the doc/design folder. Needs reviews.

**Comment by abhishekanand** [comment]
I made some minor edit to the file.

**Comment by toddschultz** [comment]
review done.
