### ISSUE TITLE
Create notebook for overall workflow

### ISSUE THREAD

**Issue by toddschultz** [toddschultz/DegreesOfClimateChange#17]
# Notebook
Create Jupyter Notebook for the overall workflow and comparison between the different data sources. The notebook shall be structured like a technical paper and a how-to guide. Some thoughts on sections include an introduction, data sources, comparison, conclusions, and references.

**Comment by abhishekanand** [comment]
updated function name from grab_berkeley to grab_berkeleydf.

**Comment by toddschultz** [comment]
Created a new, 'final' version of the notebook to merge all individual work into. See GlobalTemperatureComparison-Final.ipynb in the examples folder. Please commit and push changes as quickly as possible.

**Comment by toddschultz** [comment]
draft notebook done.
