### ISSUE TITLE
Final Sprint  : 5th June 2018 

### ISSUE THREAD

**Issue by abhishekanand** [toddschultz/DegreesOfClimateChange#23]
> Code 
* Unit Test  :  completed 
* grab data function :  Completed 
* Finish draft of the jupyter notebook
* Our "scientific" analysis, observations, etc, in the jupyter notebook
* update README.m 
* Create setup.py
* update design document 
* Complete this issue and :bowtie:
* Q : Do we have to generate documentation  from doctring . 

> Deliverable 
* Draft Presentation: Due date 29th May  
* Final presentation: Due date  5th June

**Comment by toddschultz** [comment]
Provided minor update to readme.md, updated Components.md, and created 'final' version of the notebook for merging.

**Comment by rrbirmiw** [comment]
^^^ Done. Also updated readme.md

**Comment by rrbirmiw** [comment]
Added a plot to the Final notebook converting anomaly data to absolute using 20th century global average temperature as the baseline/reference, then plotted on same figure (Figure III in the Comparison section), and....what do you know, ....the gradient of temperature change goes: 

Berkeley > NOAA > Worldbank

**Comment by abhishekanand** [comment]
Somehow, I am not able to run Final Jupyter notebook due to some local setting and unable to fix it. 
Nothing wrong with code its just my local setting.

**Comment by toddschultz** [comment]
class over!
