### ISSUE TITLE
Summary feedback

### ISSUE THREAD

**Issue by toddschultz** [toddschultz/DegreesOfClimateChange#25]
1. put plotting code into functions and take out of the notebook
2. Make sure the research questions are highlighted and easy to find in the notebook
3. clean up the directory
4. Design doc...tweak and finalize...i.e. really show the 'template' of how the grab_functions work
5. Unittest for the offline code needed for the notebook????
6. Add observations for each plot in the notebook

**Comment by abhishekanand** [comment]
Highlight Test case & Design Doc during presentation

**Comment by toddschultz** [comment]
Started plot_funcitons.py to capture all plot code from the notebook.

**Comment by toddschultz** [comment]
Class over!
