### ISSUE TITLE
Create python function to interact with NOAA data source

### ISSUE THREAD

**Issue by toddschultz** [toddschultz/DegreesOfClimateChange#3]
NOAA
https://www.ncdc.noaa.gov/data-access
https://www.ncdc.noaa.gov/cdo-web/webservices/v2

An overview of the data access available from NOAA is at:
https://www.ncdc.noaa.gov/data-access

The documentation for the NOAA RESTful Web Services v2 API is at:
https://www.ncdc.noaa.gov/cdo-web/webservices/v2

Reference documents from NOAA can be found at:
ftp://ftp.ncdc.noaa.gov/pub/data/noaa/

Instructions for obtaining an API key:
1. Go to <https://www.ncdc.noaa.gov/cdo-web/token> and submit a token request.
2. Open the "NOAAtokenTemplate.txt" file and enter the email address used to obtain the NOAA API token and the token itself into the second line of the file. 
3. Save the file as "NOAAtoken.txt" in the same directory with the template file and the python module.

**Comment by toddschultz** [comment]
The API doesn't have the averaged data. The global averaged temperature is actually in 

https://www.ncdc.noaa.gov/cag/global/time-series/globe/land_ocean/1/2/1880-2017

However, the data is in the form of a deviation from a mean. I think it will be better to use absolute temperature so I'll have to add the mean temperature back in.

**Comment by toddschultz** [comment]
I've completed a draft grab_noaa module. However, the returned temperature is the temperature anomaly to the 20th-century average. The temperature cannot be easily converted back to an absolute temperature since the normalization is performed on a regional basis before the global averaging. I think we're going to have to deal with differences in the provided data in the Jupyter notebook.

**Comment by abhishekanand** [comment]
Added example of the function output in doc string and commented print instruction.

**Comment by toddschultz** [comment]
function done for now. new bug/enhancements to be posted as new issues.
