### ISSUE TITLE
Clean Doc folder in the repo .

### ISSUE THREAD

**Issue by abhishekanand** [toddschultz/DegreesOfClimateChange#7]
# Issue Template
Clean Doc folder in the repo.

**Comment by toddschultz** [comment]
Cleaned up some of the repo structure. All files from the notes folder have been moved. New design folder in the doc directory for all design/requirements documents. Some other unneeded files and folders deleted.

**Comment by toddschultz** [comment]
I think this is all done for the doc folder. Closing issue.
